export const HeroTabSelector = () => {
  return (
    <div className="relative items-center box-border caret-transparent flex flex-col justify-start min-h-[auto] min-w-[auto] outline-[3px] w-full mt-7">
      <div className="relative items-center bg-gray-900/10 box-border caret-transparent gap-x-1 flex justify-center min-h-[auto] min-w-[auto] outline-[3px] gap-y-1 z-[3] p-1 rounded-2xl">
        <div className="relative text-gray-900 items-center box-border caret-transparent gap-x-1.5 flex h-9 justify-center min-h-[auto] min-w-[auto] outline-[3px] gap-y-1.5 z-[2] pl-2 pr-2.5">
          <div className="items-center box-border caret-transparent flex h-[18px] justify-center min-h-[auto] min-w-[auto] outline-[3px] w-[18px] before:accent-auto before:caret-transparent before:text-gray-900 before:table before:text-xl before:not-italic before:normal-nums before:font-normal before:col-end-2 before:col-start-1 before:row-end-2 before:row-start-1 before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-inter after:accent-auto after:caret-transparent after:clear-both after:text-gray-900 after:table after:text-xl after:not-italic after:normal-nums after:font-normal after:col-end-2 after:col-start-1 after:row-end-2 after:row-start-1 after:tracking-[normal] after:leading-7 after:list-outside after:list-disc after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:pointer-events-auto after:text-center after:no-underline after:indent-[0px] after:normal-case after:visible after:border-separate after:font-inter">
            <img
              src="https://c.animaapp.com/mnxsvuft69auLT/assets/icon-2.svg"
              alt="Icon"
              className="box-border caret-transparent flex h-[18px] outline-[3px] align-baseline w-[18px]"
            />
          </div>
          <div className="text-sm font-medium box-border caret-transparent leading-5 min-h-[auto] min-w-[auto] outline-[3px]">
            Demo
          </div>
        </div>
        <div className="relative text-white items-center box-border caret-transparent gap-x-1.5 flex h-9 justify-center min-h-[auto] min-w-[auto] outline-[3px] gap-y-1.5 z-[2] pl-2 pr-2.5">
          <div className="items-center box-border caret-transparent flex h-[18px] justify-center min-h-[auto] min-w-[auto] outline-[3px] w-[18px] before:accent-auto before:caret-transparent before:text-white before:table before:text-xl before:not-italic before:normal-nums before:font-normal before:col-end-2 before:col-start-1 before:row-end-2 before:row-start-1 before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-inter after:accent-auto after:caret-transparent after:clear-both after:text-white after:table after:text-xl after:not-italic after:normal-nums after:font-normal after:col-end-2 after:col-start-1 after:row-end-2 after:row-start-1 after:tracking-[normal] after:leading-7 after:list-outside after:list-disc after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:pointer-events-auto after:text-center after:no-underline after:indent-[0px] after:normal-case after:visible after:border-separate after:font-inter">
            <img
              src="https://c.animaapp.com/mnxsvuft69auLT/assets/icon-3.svg"
              alt="Icon"
              className="box-border caret-transparent flex h-[18px] outline-[3px] align-baseline w-[18px]"
            />
          </div>
          <div className="text-sm font-medium box-border caret-transparent leading-5 min-h-[auto] min-w-[auto] outline-[3px]">
            Video
          </div>
        </div>
        <div className="absolute bg-white shadow-[rgba(17,24,39,0.12)_0px_0px_0px_1px,rgba(17,24,39,0.03)_0px_2px_2px_-2px,rgba(17,24,39,0.03)_0px_4px_4px_0px,rgba(17,24,39,0.03)_0px_8px_8px_0px,rgba(17,24,39,0.03)_0px_16px_16px_0px] box-border caret-transparent h-9 min-w-5 outline-[3px] pointer-events-none w-[81px] z-[1] rounded-xl left-1 inset-y-1"></div>
      </div>
      <div className="relative items-center bg-white shadow-[rgba(17,24,39,0.12)_0px_0px_0px_1px,rgba(17,24,39,0.03)_0px_2px_2px_-2px,rgba(17,24,39,0.03)_0px_4px_4px_0px,rgba(17,24,39,0.03)_0px_8px_8px_0px,rgba(17,24,39,0.03)_0px_16px_16px_0px] box-border caret-transparent flex h-[72px] justify-between max-w-[468px] min-h-[auto] min-w-[auto] outline-[3px] w-full mt-4 px-4 rounded-3xl scale-95 md:px-6">
        <div className="items-center box-border caret-transparent gap-x-3 flex justify-start min-h-[auto] min-w-[auto] outline-[3px] gap-y-3 w-full">
          <div className="box-border caret-transparent min-h-[auto] min-w-[auto] outline-[3px] w-full before:accent-auto before:caret-transparent before:text-gray-600 before:table before:text-xl before:not-italic before:normal-nums before:font-normal before:col-end-2 before:col-start-1 before:row-end-2 before:row-start-1 before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-inter after:accent-auto after:caret-transparent after:clear-both after:text-gray-600 after:table after:text-xl after:not-italic after:normal-nums after:font-normal after:col-end-2 after:col-start-1 after:row-end-2 after:row-start-1 after:tracking-[normal] after:leading-7 after:list-outside after:list-disc after:outline-[3px] after:pointer-events-auto after:text-center after:no-underline after:indent-[0px] after:normal-case after:visible after:border-separate after:font-inter">
            <form className="relative text-gray-900 text-base items-center box-border caret-transparent flex justify-start outline-[3px] w-full md:text-lg">
              <input
                type="text"
                placeholder="https://yourwebsite.com"
                className="text-base bg-transparent box-border caret-transparent block h-[72px] leading-[72px] min-h-[auto] min-w-[auto] object-contain outline-[3px] text-start align-middle w-full pl-0 pr-2 py-0 md:text-lg"
              />
              <button
                type="submit"
                className="relative text-base items-center bg-blue-700 shadow-[rgb(24,47,165)_0px_0px_0px_1px,rgba(17,24,39,0.04)_0px_2px_2px_-2px,rgba(17,24,39,0.04)_0px_4px_4px_0px,rgba(17,24,39,0.04)_0px_8px_8px_0px,rgba(17,24,39,0.04)_0px_16px_16px_0px,rgba(17,24,39,0.04)_0px_32px_32px_0px] caret-transparent flex shrink-0 h-9 justify-center min-h-[auto] min-w-[auto] outline-[3px] w-9 z-[1] p-0 rounded-[72px] md:text-lg hover:bg-indigo-600 hover:shadow-[rgb(33,66,231)_0px_0px_0px_1px,rgba(17,24,39,0.04)_0px_2px_2px_-2px,rgba(17,24,39,0.04)_0px_4px_4px_0px,rgba(17,24,39,0.04)_0px_8px_8px_0px,rgba(17,24,39,0.04)_0px_16px_16px_0px,rgba(17,24,39,0.04)_0px_32px_32px_0px]"
              >
                <img
                  src="https://c.animaapp.com/mnxsvuft69auLT/assets/icon-4.svg"
                  alt="Icon"
                  className="absolute text-base box-border caret-transparent h-5 outline-[3px] align-baseline w-5 z-[2] md:text-lg"
                />
                <div className="relative text-base items-center box-border caret-transparent hidden h-5 justify-start outline-[3px] w-5 md:text-lg">
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                  <div className="absolute text-base items-start box-border caret-transparent flex h-full left-[calc(50%_-_1px)] outline-[3px] w-0.5 top-0 md:text-lg before:accent-auto before:bg-white before:caret-transparent before:text-gray-900 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[22%] before:tracking-[normal] before:leading-7 before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-center before:no-underline before:indent-[0px] before:normal-case before:origin-[50%_100%] before:visible before:w-full before:rounded-[1px] before:border-separate before:font-inter before:md:text-lg"></div>
                </div>
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};
